

server:
    port: 20001
  
  
security:
    base: 
        enabled: false
        path: /**
    user:
        name: username
        password: 20161001
        #role: USER
    oauth2:
        authorization:
            checkTokenAccess=isAuthenticated()
        client:
            client-id: myclient
            client-secret: democlient
        resource:
            id: demo2016
            service-id: demo201605
            token-type: authorizationCodeService
            token-info-uri: http://127.0.0.1:20001/hello
            
spring:
    datasource:
        test-while-idle: true
        test-on-connect: true
        validation-query: select 1
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test_oauth2?useUnicode=true&characterEncoding=utf8
        username: demo
        password: demo
                    